version: '3'
services:
  worker:
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file: .env
    volumes:
      - .:/app
    depends_on: 
      - database
  database:
    image: postgres:alpine
    environment: 
      - POSTGRES_PASSWORD
    volumes:
      - ./db:/docker-entrypoint-initdb.d
